config/routes.rb
Rails.application.routes.draw do

  resources :songs

  get '/', to: 'application#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  has_many :genres, through: :songs
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :song_genres
  has_many :songs, through: :song_genres
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_many :song_genres
  has_many :genres, through: :song_genres
end

app/models/song_genre.rb
class SongGenre < ApplicationRecord
  belongs_to :song
  belongs_to :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def index
    render :index
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
 
  before_action :set_song, only: [:show, :destroy]

  def set_song
    @song = Song.find(params[:id])
  end

  def index
    @songs = Song.all
  end

  def show
  end

  def destroy
    @song.destroy
    redirect_to '/songs'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<h1>Rails Playlister</h1>
<a href="/songs">All Songs</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPlaylister</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/index.html.erb
<h1>All Songs</h1>
<% @songs.each do |song| %>
  <%= link_to song.name, song_path(song) %><br>
<% end %>

<br>
<a href='/'>Home</a>

app/views/songs/show.html.erb
<h1><%= @song.name %></h1>
<h2>by <%= @song.artist.name %></h2>

<% @song.genres.each do |genre| %>
  <%= genre.name %><br>
  <% end %>

<br><br>
<!-- <%= link_to "Delete", '/songs/[][song.id]', method: :delete %> -->
<%= link_to "Delete", "/songs/#{@song.id}", method: :delete %>